# -*- coding: utf-8 -*-
import io
P = "/Users/lili/Desktop/deepseek harness/老板确认看板/boss-dashboard-v6.html"
src = io.open(P, encoding="utf-8").read()
REPS = []
def R(old, new, expect=1, name=""):
    REPS.append((old, new, expect, name))
R("const SEGMENTS = [\n  { name:'APR（整体）', code:'APR', sales:688842, gross:21345, gpm:3.10, cvr:null, feeRate:null, inv:1442.6, d7:null, yoy:72.8, onlineShare:30.7, offlineShare:69.3, note:'10 家门店 · 含线上线下整体' },\n  { name:'Apple 电商', code:'AE', sales:367479, gross:18294, gpm:4.98, cvr:null, feeRate:null, inv:367.5, d7:null, yoy:89.2, onlineShare:100, offlineShare:0, note:'京东羽通/苏宁啟韬/响誉' },\n  { name:'Shure 电商', code:'SH', sales:24708, gross:7489, gpm:30.31, cvr:null, feeRate:null, inv:229.5, d7:null, yoy:15.5, onlineShare:100, offlineShare:0, note:'天猫（吉客云口径）' },\n  { name:'分销/其他', code:'OTH', sales:11108, gross:475, gpm:4.27, cvr:null, feeRate:null, inv:0, d7:null, yoy:-88.9, onlineShare:0, offlineShare:100, note:'分销 + 天羽乐购' }\n];", "const SEGMENTS = [\n  { name:'APR（整体）', code:'APR', sales:688842, gross:21345, gpm:3.10, cvr:null, feeRate:null, inv:1442.6, d7:null, yoy:72.8, onlineShare:30.7, offlineShare:69.3, note:'10 家门店 · 含线上线下整体' },\n  { name:'Apple 电商', code:'AE', sales:367479, gross:18294, gpm:4.98, cvr:null, feeRate:null, inv:367.5, d7:null, yoy:89.2, onlineShare:100, offlineShare:0, note:'啟韬(苏宁)+羽通(京东)·其余 3.7 万未细分',\n    stores:[\n      { name:'苏宁旗舰店（啟韬）', sales:220880, gross:5478, gpm:2.48, cvr:null, feeRate:null, inv:103.5, d7:null, yoy:null, src:'吉客云自动' },\n      { name:'京东旗舰店（羽通）', sales:145332, gross:14418, gpm:9.92, cvr:null, feeRate:null, inv:264.0, d7:null, yoy:null, src:'吉客云自动' }\n    ] },\n  { name:'Shure 电商', code:'SH', sales:24708, gross:7489, gpm:30.31, cvr:null, feeRate:null, inv:229.5, d7:null, yoy:15.5, onlineShare:100, offlineShare:0, note:'天猫(吉客云自动)+京东(日报手工另计)',\n    stores:[\n      { name:'天猫旗舰店', sales:24709, gross:7489, gpm:30.31, cvr:null, feeRate:null, inv:137.3, d7:null, yoy:15.5, src:'吉客云自动' },\n      { name:'京东旗舰店（另计）', sales:24726, gross:0, gpm:null, cvr:3.15, feeRate:null, inv:92.2, d7:null, yoy:null, src:'平台日报·手工' }\n    ] },\n  { name:'分销/其他', code:'OTH', sales:11108, gross:475, gpm:4.27, cvr:null, feeRate:null, inv:0, d7:null, yoy:-88.9, onlineShare:0, offlineShare:100, note:'分销 + 天羽乐购' }\n];", 1, 'SEGMENTS分店')
R("function d7Html(v){ return v==null?'—':`<span class=\"${v>=0?'pos':'neg'}\">${v>=0?'+':''}${v.toFixed(1)}%</span>`; }", "function d7Html(v){ return v==null?'—':`<span class=\"${v>=0?'pos':'neg'}\">${v>=0?'+':''}${v.toFixed(1)}%</span>`; }\nfunction segSubRows(s){\n  if(!s.stores||!s.stores.length) return '';\n  return s.stores.map(x=>{\n    const src = x.src?` <small style=\"color:#8a9aab\">${esc(x.src)}</small>`:'';\n    return `<tr style=\"background:#f7fafd\"><td class=\"t-name\" style=\"padding-left:24px\">└ ${esc(x.name)}${src}</td><td>${fmtY(mul(x.sales))}</td><td>${fmtWan(mul(x.gross))}</td><td>${pct(x.gpm)}</td><td>${x.cvr!=null?pct(x.cvr):'待接入'}</td>${isMonth()?`<td>${fee(x.feeRate)}</td>`:''}<td>¥${x.inv}万</td><td>${(x.sales/COMPANY.day.sales*100).toFixed(1)}%</td><td>${d7Html(x.d7)}</td><td>${x.yoy!=null?`<span class=\"${x.yoy>=0?'pos':'neg'}\">${x.yoy>=0?'+':''}${x.yoy.toFixed(1)}%</span>`:'待接入'}</td></tr>`;\n  }).join('');\n}", 1, 'segSubRows')
R("    return tableCard('业务板块对比（'+pl+'）', feeHead, ['业务板块','销售额','毛利额','毛利率','转化率', ...(isMonth()?['费率']:[]), '库存','占比','环比','同比'], SEGMENTS.map(cells).join('')+tRow);", "    return tableCard('业务板块对比（'+pl+'）', feeHead, ['业务板块','销售额','毛利额','毛利率','转化率', ...(isMonth()?['费率']:[]), '库存','占比','环比','同比'], SEGMENTS.map(s=>cells(s)+segSubRows(s)).join('')+tRow);", 1, '简报分店行')
R("  const segRows = SEGMENTS.map(s=>{\n    const share = s.sales/COMPANY.day.sales*100;\n    return `<tr><td class=\"t-name\">${esc(s.name)}<br><small style=\"color:#8a9aab\">${esc(s.note)}</small></td><td>${fmtY(mul(s.sales))}</td><td>${fmtWan(mul(s.gross))}</td><td>${pct(s.gpm)}</td><td>${pct(s.cvr)}</td><td>${isMonth()?fee(s.feeRate):'<span style=\"color:#c6d2dd\">—</span>'}</td><td>¥${s.inv}万</td><td>${share.toFixed(1)}%</td><td>${d7Html(s.d7)}</td><td><span class=\"${s.yoy>=0?'pos':'neg'}\">${s.yoy>=0?'+':''}${s.yoy.toFixed(1)}%</span></td></tr>`;\n  }).join('');", "  const segRows = SEGMENTS.map(s=>{\n    const share = s.sales/COMPANY.day.sales*100;\n    const mainRow = `<tr><td class=\"t-name\">${esc(s.name)}<br><small style=\"color:#8a9aab\">${esc(s.note)}</small></td><td>${fmtY(mul(s.sales))}</td><td>${fmtWan(mul(s.gross))}</td><td>${pct(s.gpm)}</td><td>${pct(s.cvr)}</td><td>${isMonth()?fee(s.feeRate):'<span style=\"color:#c6d2dd\">—</span>'}</td><td>¥${s.inv}万</td><td>${share.toFixed(1)}%</td><td>${d7Html(s.d7)}</td><td><span class=\"${s.yoy>=0?'pos':'neg'}\">${s.yoy>=0?'+':''}${s.yoy.toFixed(1)}%</span></td></tr>`;\n    return mainRow + segSubRows(s);\n  }).join('');", 1, '渠道对比分店行')
R("const AE_STORES = [\n  { name:'京东旗舰店（羽通）', sales:145332, gpm:9.92, gross:14417, uv:null, cvr:null, refund:null, d7:null, yoy:null },\n  { name:'苏宁旗舰店（啟韬）', sales:220880, gpm:2.48, gross:5478, uv:null, cvr:null, refund:null, d7:null, yoy:null },\n  { name:'天猫旗舰店（响誉）', sales:58, gpm:null, gross:58, uv:null, cvr:null, refund:null, d7:null, yoy:null }\n];", "const AE_STORES = [\n  { name:'苏宁旗舰店（啟韬）', sales:220880, gpm:2.48, gross:5478, uv:null, cvr:null, refund:null, d7:null, yoy:null, task:901.47, rate:71.6, src:'吉客云自动' },\n  { name:'京东旗舰店（羽通）', sales:145332, gpm:9.92, gross:14418, uv:null, cvr:null, refund:null, d7:null, yoy:null, task:3140.13, rate:13.5, src:'吉客云自动' }\n];", 1, 'AE_STORES 2店')
R("const SH_STORES = [\n  { name:'京东旗舰店', sales:24726, gpm:null, gross:0, uv:24172, cvr:3.15, refund:null, d7:null, yoy:null },\n  { name:'天猫旗舰店', sales:24709, gpm:30.31, gross:7489, uv:null, cvr:null, refund:null, d7:null, yoy:null }\n];", "const SH_STORES = [\n  { name:'天猫旗舰店', sales:24709, gpm:30.31, gross:7489, uv:null, cvr:null, refund:null, d7:null, yoy:15.5, task:220, rate:32.8, src:'吉客云自动' },\n  { name:'京东旗舰店', sales:24726, gpm:null, gross:0, uv:24172, cvr:3.15, refund:null, d7:null, yoy:null, task:210, rate:34.4, src:'平台日报·手工' }\n];", 1, 'SH_STORES 加目标')
R("  const k1 = kpiCard('销售总额',fmtY(mul(total)),null,'3 家店铺合计 · 分摊后口径（含在途）','red');", "  const k1 = kpiCard('销售总额',fmtY(mul(total)),null,'2 家店铺合计（啟韬+羽通）· 分摊后口径（含在途）','red');", 1, 'AE k1')
R("  const rows = AE_STORES.map(s=>`<tr><td class=\"t-name\">${esc(s.name)}</td><td>${fmtY(mul(s.sales))}</td><td>${fmtWan(mul(s.gross))}</td><td>${pct(s.gpm)}</td><td>${s.uv!=null?s.uv.toLocaleString():'待接入'}</td><td>${pct(s.cvr)}</td><td>${s.refund!=null?`<span class=\"${s.refund>2.5?'neg':'pos'}\">${pct(s.refund)}</span>`:'待接入'}</td><td>${d7Html(s.d7)}</td><td>${s.yoy!=null?`<span class=\"${s.yoy>=0?'pos':'neg'}\">${s.yoy>=0?'+':''}${s.yoy.toFixed(1)}%</span>`:'待接入'}</td></tr>`).join('');", "  const rows = AE_STORES.map(s=>`<tr><td class=\"t-name\">${esc(s.name)}<br><small style=\"color:#8a9aab\">${esc(s.src)}</small></td><td>${fmtY(mul(s.sales))}</td><td>¥${s.task}万</td><td><span class=\"${s.rate>=65?'pos':s.rate>=50?'':'neg'}\">${s.rate.toFixed(1)}%</span></td><td>${pct(s.gpm)}</td><td>${s.uv!=null?s.uv.toLocaleString():'待接入'}</td><td>${pct(s.cvr)}</td></tr>`).join('');", 1, 'AE rows')
R("      ${tableCard('店铺经营对比','销售 / 毛利 / 流量 / 转化 / 退款 / 环比 / 同比（流量类明早接入）',['店铺','销售额','毛利额','毛利率','访客数','支付转化','退款率','环比','同比'],rows)}", "      ${tableCard('店铺经营对比（啟韬 / 羽通）','目标为财务 8 月表（待运营确认）· 流量明早接入',['店铺','销售额','目标','达成率','毛利率','访客数','转化率'],rows)}", 1, 'AE表头')
R("      concl:'Apple 电商 8/1-26 销售 '+fmtY(mul(total))+'（分摊后、含在途），毛利率 4.98%；在途订单占比高（发货在途 567 万）。',\n      anom:'在途 567 万 / 待审核 69 万需关注发货时效；京东羽通毛利率 9.92% 为正、苏宁啟韬 2.48% 偏低。',\n      act:'① 核查在途订单发货时效与退款风险；② 与运营确认 8 月目标口径（财务表 4,042 万 vs 实际 1,073 万，达成 26.5%）；③ 明早接入各店流量/转化。'", "      concl:'Apple 电商 8/1-26 销售 '+fmtY(mul(total))+'（分摊后、含在途），毛利率 4.98%；分店：苏宁啟韬 645 万/达成 71.6%、京东羽通 424 万/达成 13.5%。',\n      anom:'京东羽通目标 3,140 万 vs 实际 424 万，达成仅 13.5%，需重点核查口径（国补/在途/京东自营是否另计）；在途 567 万/待审核 69 万。',\n      act:'① 与运营确认羽通/啟韬目标口径；② 在途发货时效核查；③ 明早接入两店流量/转化。'", 1, 'AE分析')
R("  const k1 = kpiCard('销售总额',fmtY(mul(total)),null,'天猫(吉客云)+京东(平台日报)','green');", "  const k1 = kpiCard('销售总额',fmtY(mul(total)),null,'天猫(吉客云自动)+京东(日报手工)','green');", 1, 'SH k1')
R("  const rows = SH_STORES.map(s=>`<tr><td class=\"t-name\">${esc(s.name)}</td><td>${fmtY(mul(s.sales))}</td><td>${fmtWan(mul(s.gross))}</td><td>${pct(s.gpm)}</td><td>${s.uv!=null?s.uv.toLocaleString():'待接入'}</td><td>${pct(s.cvr)}</td><td>${s.refund!=null?pct(s.refund):'待接入'}</td><td>${d7Html(s.d7)}</td><td>${s.yoy!=null?`<span class=\"${s.yoy>=0?'pos':'neg'}\">${s.yoy>=0?'+':''}${s.yoy.toFixed(1)}%</span>`:'待接入'}</td></tr>`).join('');", "  const rows = SH_STORES.map(s=>`<tr><td class=\"t-name\">${esc(s.name)}<br><small style=\"color:#8a9aab\">${esc(s.src)}</small></td><td>${fmtY(mul(s.sales))}</td><td>¥${s.task}万</td><td><span class=\"${s.rate>=65?'pos':s.rate>=50?'':'neg'}\">${s.rate.toFixed(1)}%</span></td><td>${pct(s.gpm)}</td><td>${s.uv!=null?s.uv.toLocaleString():'待接入'}</td><td>${pct(s.cvr)}</td></tr>`).join('');", 1, 'SH rows')
R("      ${tableCard('店铺经营对比','天猫为吉客云口径；京东为平台日报口径（72.2 万，未计入公司合计）',['店铺','销售额','毛利额','毛利率','访客数','转化率','退款率','环比','同比'],rows)}", "      ${tableCard('店铺经营对比（天猫 / 京东）','目标为财务 8 月表 · 京东为平台日报手工口径',['店铺','销售额','目标','达成率','毛利率','访客数','转化率'],rows)}", 1, 'SH表头')
R("      concl:'Shure 电商：天猫 8/1-26 销售 72.15 万（吉客云、含在途）、毛利率 30.31%；京东 8/1-25 销售 72.2 万（平台日报）。',\n      anom:'天猫流量/转化数据待明早导出（模板含 8/1-16 部分数据）；京东 8/26 数据待补。',\n      act:'① 明早接入天猫/京东完整流量与转化；② 天猫转化率（8/1-16 约 0.72%）低于京东 3.15%，重点优化。'", "      concl:'Shure 电商：天猫 72.15 万/达成 32.8%（目标 220 万）·吉客云自动；京东 72.2 万/达成 34.4%（目标 210 万）·日报手工（8/1-25）。',\n      anom:'天猫流量待明早导出（模板到 8/16，转化 0.72%）；京东 8/26 待补；京东毛利率无数据（未计入合计）。',\n      act:'① 明早接天猫完整流量/转化；② 京东按日报手工更新；③ 两店转化对标优化（天猫 0.72% vs 京东 3.15%）。'", 1, 'SH分析')
R("aiTip('8/1-26 已支付销售额 <b>¥3,189 万</b>（分摊后口径），同比 +45.8%；APR 板块贡献 63.1% 为增长主引擎，日照（147.5%）与彭城（128.3%）达成领先；Apple 电商达成 26.5% 需重点核查。')", "aiTip('8/1-26 已支付销售额 <b>¥3,189 万</b>（分摊后口径），同比 +45.8%；APR 板块贡献 63.1% 为增长主引擎；Apple 电商分店：啟韬 71.6% / 羽通 13.5%，羽通目标口径需核查；Shure 天猫(自动)+京东(日报手工) 已分店展示。')", 1, '简报aiTip')
ok = True
for old, new, expect, name in REPS:
    n = src.count(old)
    if n != expect:
        print("MISS/COUNT[%s]: expected %d, got %d" % (name, expect, n))
        ok = False
    else:
        src = src.replace(old, new)
        print("ok  [%s]" % name)
io.open(P, "w", encoding="utf-8").write(src)
print(); print('PART7 done, ok =', ok)