# -*- coding: utf-8 -*-
import io, base64
P = "/Users/lili/Desktop/deepseek harness/老板确认看板/boss-dashboard-v6.html"
src = io.open(P, encoding='utf-8').read()
REPS = []
def R(old, new, expect=1, name=""):
    REPS.append((old, new, expect, name))
newb64 = base64.b64encode(open('/Users/lili/Desktop/deepseek harness/dsh_keys/logo_white.png','rb').read()).decode()
import re
def repl_logo(m): return 'data:image/png;base64,' + newb64
src2, nlogo = re.subn(r'data:image/png;base64,[A-Za-z0-9+/=]+', repl_logo, src)
print('logo 替换:', nlogo, '处'); src = src2
R(".b-logo-img{display:block;width:100%;height:auto;max-height:66px;object-fit:contain;margin:0 0 12px;background:#fff;border-radius:12px;padding:7px 10px;box-shadow:0 4px 14px rgba(0,0,0,.22)}", ".b-logo-img{display:block;width:96%;height:auto;max-height:74px;object-fit:contain;margin:2px auto 14px;filter:drop-shadow(0 3px 8px rgba(0,0,0,.45))}", 1, 'logo白底CSS')
R("  const k5 = kpiCard('综合转化率', pct(c.cvr), -0.2, '线下/线上转化率待接入', '');\n", "", 2, '删k5行')
R("<div class=\"metric-grid\">${k1}${k2}${k3}${k4}${k5}${k6}${k7}${k8}</div>", "<div class=\"metric-grid\">${k1}${k2}${k3}${k4}${k6}${k7}${k8}</div>", 2, '删k5引用')
R("/* 三大板块（日度基数，含同比/环比/占比/线上线下） */", "/* 三大板块（日度基数，含同比/环比/占比/线上线下） */\nconst BUSINESS_ROWS = [\n  { name:'APR（整体）', code:'APR', sales:688842, gross:21345, gpm:3.10, cvr:null, feeRate:null, inv:1442.6, d7:null, yoy:72.8, note:'10 家门店 · 含线上线下' },\n  { name:'京东羽通（Apple 电商）', code:'AE', sales:145332, gross:14418, gpm:9.92, cvr:null, feeRate:null, inv:264.0, d7:null, yoy:89.2, note:'苹果电商 · 京东' },\n  { name:'苏宁啟韬（Apple 电商）', code:'AE', sales:220880, gross:5478, gpm:2.48, cvr:null, feeRate:null, inv:103.5, d7:null, yoy:89.2, note:'苹果电商 · 苏宁' },\n  { name:'天猫舒尔', code:'SH', sales:24709, gross:7489, gpm:30.31, cvr:0.88, feeRate:null, inv:137.3, d7:null, yoy:15.5, note:'吉客云自动' },\n  { name:'京东舒尔（平台日报）', code:'SH', sales:25592, gross:0, gpm:null, cvr:3.12, feeRate:null, inv:92.2, d7:null, yoy:null, note:'平台日报 · 手工' }\n];\nfunction bizRowsHtml(){\n  const rows = BUSINESS_ROWS;\n  const tot = rows.reduce((a,b)=>({sales:a.sales+b.sales, gross:a.gross+b.gross, inv:a.inv+b.inv}), {sales:0,gross:0,inv:0});\n  const gpm = tot.gross/tot.sales*100;\n  const feeCol = isMonth();\n  const totalRow = `<tr style=\"background:#e8f0fa\"><td class=\"t-name\">合计（含京东舒尔·平台口径）</td><td><b>${fmtY(mul(tot.sales))}</b></td><td><b>${fmtWan(mul(tot.gross))}</b></td><td><b>${pct(gpm)}</b></td><td>—</td>${feeCol?`<td><b>${fee(null)}</b></td>`:''}<td><b>¥${tot.inv.toFixed(0)}万</b></td><td>100%</td><td>${d7Html(null)}</td><td><span class=\"pos\">+${COMPANY.day.yoy.toFixed(1)}%</span></td></tr>`;\n  const body = rows.map(s=>{\n    const share = s.sales/tot.sales*100;\n    return `<tr><td class=\"t-name\">${esc(s.name)}${s.note?`<br><small style=\"color:#8a9aab\">${esc(s.note)}</small>`:''}</td><td>${fmtY(mul(s.sales))}</td><td>${fmtWan(mul(s.gross))}</td><td>${pct(s.gpm)}</td><td>${pct(s.cvr)}</td>${feeCol?`<td>${fee(s.feeRate)}</td>`:''}<td>¥${s.inv}万</td><td>${share.toFixed(1)}%</td><td>${d7Html(s.d7)}</td><td>${s.yoy!=null?`<span class=\"${s.yoy>=0?'pos':'neg'}\">${s.yoy>=0?'+':''}${s.yoy.toFixed(1)}%</span>`:'未接入'}</td></tr>`;\n  }).join('');\n  return totalRow + body + totalRow;\n}", 1, 'BUSINESS_ROWS')
R("      ${(()=>{\n    const feeCol = isMonth() ? '<th>费率</th>' : '';\n    const feeHead = isMonth() ? '销售 / 毛利 / 转化 / 费率 / 库存 / 占比 / 环比 / 同比' : '销售 / 毛利 / 转化 / 库存 / 占比 / 环比 / 同比';\n    const cells = s=>`<td class=\"t-name\">${esc(s.name)}</td><td>${fmtY(mul(s.sales))}</td><td>${fmtWan(mul(s.gross))}</td><td>${pct(s.gpm)}</td><td>${pct(s.cvr)}</td>${isMonth()?`<td>${fee(s.feeRate)}</td>`:''}<td>¥${s.inv}万</td><td>${(s.sales/COMPANY.day.sales*100).toFixed(1)}%</td><td>${d7Html(s.d7)}</td><td><span class=\"${s.yoy>=0?'pos':'neg'}\">${s.yoy>=0?'+':''}${s.yoy.toFixed(1)}%</span></td>`;\n    const tRow = `<tr style=\"background:#f0f6fc\"><td class=\"t-name\">合计</td><td><b>${fmtY(mul(COMPANY.day.sales))}</b></td><td><b>${fmtWan(mul(COMPANY.day.gross))}</b></td><td><b>${pct(COMPANY.day.gpm)}</b></td><td>—</td>${isMonth()?`<td><b>${fee(COMPANY.day.feeRate)}</b></td>`:''}<td><b>¥${INV_BIZ.total_amount.toFixed(0)}万</b></td><td>100%</td><td>${d7Html(COMPANY.day.d7)}</td><td><span class=\"pos\">+${COMPANY.day.yoy.toFixed(1)}%</span></td></tr>`;\n    return tableCard('业务板块对比（'+pl+'）', feeHead, ['业务板块','销售额','毛利额','毛利率','转化率', ...(isMonth()?['费率']:[]), '库存','占比','环比','同比'], SEGMENTS.map(cells).join('')+tRow);\n  })()}", "      ${(()=>{\n    const feeHead = isMonth() ? '销售 / 毛利 / 转化 / 费率 / 库存 / 占比 / 环比 / 同比' : '销售 / 毛利 / 转化 / 库存 / 占比 / 环比 / 同比';\n    return tableCard('业务板块对比（'+pl+'）', feeHead, ['业务板块','销售额','毛利额','毛利率','转化率', ...(isMonth()?['费率']:[]), '库存','占比','环比','同比'], bizRowsHtml());\n  })()}", 1, '简报表重构')
R("  const segRows = SEGMENTS.map(s=>{\n    const share = s.sales/COMPANY.day.sales*100;\n    const mainRow = `<tr><td class=\"t-name\">${esc(s.name)}<br><small style=\"color:#8a9aab\">${esc(s.note)}</small></td><td>${fmtY(mul(s.sales))}</td><td>${fmtWan(mul(s.gross))}</td><td>${pct(s.gpm)}</td><td>${pct(s.cvr)}</td><td>${isMonth()?fee(s.feeRate):'<span style=\"color:#c6d2dd\">—</span>'}</td><td>¥${s.inv}万</td><td>${share.toFixed(1)}%</td><td>${d7Html(s.d7)}</td><td><span class=\"${s.yoy>=0?'pos':'neg'}\">${s.yoy>=0?'+':''}${s.yoy.toFixed(1)}%</span></td></tr>`;\n    return mainRow;\n  }).join('');\n  const totalRow = `<tr style=\"background:#f0f6fc\"><td class=\"t-name\">合计</td><td><b>${fmtY(mul(COMPANY.day.sales))}</b></td><td><b>${fmtWan(mul(COMPANY.day.gross))}</b></td><td><b>${pct(c.gpm)}</b></td><td>—</td><td><b>${fee(c.feeRate)}</b></td><td><b>¥${INV_BIZ.total_amount.toFixed(0)}万</b></td><td>100%</td><td>${d7Html(c.d7)}</td><td><span class=\"pos\">+${c.yoy.toFixed(1)}%</span></td></tr>`;", "  const segRows = bizRowsHtml();\n  const totalRow = '';", 1, '渠道对比表重构')
R("tableCard('渠道对比（'+pl+'）','APR 为整体口径（不拆线上线下）；费率仅月度出数',['业务板块','销售额','毛利额','毛利率','转化率','费率','库存','占比','环比','同比'],segRows+totalRow)", "tableCard('渠道对比（'+pl+'）','分店口径：APR整体+苹果2店+舒尔2店；含京东舒尔(平台日报)',['业务板块','销售额','毛利额','毛利率','转化率','费率','库存','占比','环比','同比'],segRows)", 1, '渠道对比表头')
R("  const k4 = kpiCard('周转天数', '待接入', null, '需销售速率数据', '');", "  const k4 = kpiCard('周转天数', '17.9 天', null, '库存 2,109 万 ÷ 近4周周均 826 万 × 7', '');", 1, '周转天数')
R("const INV_STRUCTURE = [\n  { name:'90 天以内（健康）', pct:61.9, color:'#2f69c2' },\n  { name:'90 天以上超龄', pct:38.1, color:'#c94d5c' }\n];", "const INV_STRUCTURE = [\n  { name:'90 天以内（健康）', pct:60.7, color:'#2f69c2' },\n  { name:'90 天以上超龄', pct:37.3, color:'#c94d5c' },\n  { name:'残次机', pct:2.0, color:'#7b91ad' }\n];", 1, '库存结构3段')
R(".donut:after{content:attr(data-center);position:absolute;inset:24px;background:var(--card);border-radius:50%;display:grid;place-items:center;font-weight:800;color:#415771;font-size:13px;text-align:center;line-height:1.4}", ".donut:after{content:attr(data-center);position:absolute;inset:30px;background:var(--card);border-radius:50%;display:grid;place-items:center;font-weight:800;color:#415771;font-size:13px;text-align:center;line-height:1.4}", 1, 'donut缝隙')
R("      { id:'pp3', name:'3PP', en:'3PP CHANNEL', title:'3PP 渠道看板', desc:'第三方配件渠道（当前暂未开展，保留框架待接入）。',\n        sections:[\n          { name:'销售指标', intro:'3PP 渠道销售结果', render:secPP3 },\n          { name:'销售分析', intro:'3PP 结构、来源与政策', render:secPP3Analysis }\n        ] }\n    ] },", "    ] },", 1, '删3PP部门')
R("desc:'公司渠道层面对比 + APR、Apple 电商、Shure电商、3PP 四大业务；经营板块首页先看渠道整体，再进部门看明细。',", "desc:'公司渠道层面对比 + APR、Apple 电商、Shure电商 三大业务；经营板块首页先看渠道整体，再进部门看明细。',", 1, '经营desc')
R("desc:'公司渠道层面：APR（整体，不拆线上线下）、Apple 电商、Shure电商、3PP 四大渠道对比；同行对比为季度手动填写口径。',", "desc:'公司渠道层面：APR（整体）、Apple 电商（羽通/啟韬）、Shure电商（天猫/京东）对比；同行对比为季度手动填写口径。',", 1, '整体总览desc')
R("    {code:'3PP',desc:'第三方配件渠道 · 未开展'}", "", 1, 'deptMeta删3PP')
R("function d7Html(v){ return v==null?'—':", "function d7Html(v){ return v==null?'未接入':", 1, 'd7Html未接入')
R("const todo = ()=>'<span style=\"color:#9aa8b8;font-style:italic\">待接入</span>';", "const todo = ()=>'<span style=\"color:#9aa8b8;font-style:italic\">未接入</span>';", 1, 'todo未接入')
R("function pct(v,d=1){ return v==null?'待接入':v.toFixed(d)+'%'; }", "function pct(v,d=1){ return v==null?'未接入':v.toFixed(d)+'%'; }", 1, 'pct未接入')
R("function fmtWan(v){ if(v==null) return '待接入';", "function fmtWan(v){ if(v==null) return '未接入';", 1, 'fmtWan未接入')
R("function fee(v, suffix){ if(v==null) return isMonth()?'待接入':'-';", "function fee(v, suffix){ if(v==null) return isMonth()?'未接入':'-';", 1, 'fee未接入')
R("<span class=\"empty-pill\">数据状态 · 待接入</span>", "<span class=\"empty-pill\">数据状态 · 未接入</span>", 1, 'empty未接入')
ok = True
for old, new, expect, name in REPS:
    n = src.count(old)
    if n != expect:
        print("MISS/COUNT[%s]: expected %d, got %d" % (name, expect, n))
        ok = False
    else:
        src = src.replace(old, new)
        print("ok  [%s]" % name)
io.open(P, 'w', encoding='utf-8').write(src)
print(); print('BIG done, ok =', ok)